import React, { useState } from 'react'
import './FAQ.css'

const FAQ = () => {
  const [openIndex, setOpenIndex] = useState(null)

  const faqs = [
    {
      question: 'What is an HTML color picker?',
      answer: 'An HTML color picker is a tool that helps you select colors and get their codes in various formats like HEX, RGB, and HSL. These codes can be used in HTML, CSS, and other web development projects.',
    },
    {
      question: 'What is the difference between HEX, RGB, and HSL?',
      answer: 'HEX uses hexadecimal notation (e.g., #FF5733), RGB uses red, green, and blue values (e.g., rgb(255, 87, 51)), and HSL uses hue, saturation, and lightness (e.g., hsl(9, 100%, 60%)). All three represent the same colors but in different formats.',
    },
    {
      question: 'Is this color picker free to use?',
      answer: 'Yes, our HTML color picker is completely free to use. There are no hidden fees, registration requirements, or usage limits. Use it as much as you need for all your projects.',
    },
    {
      question: 'Can I use the color codes in my projects?',
      answer: 'Absolutely! The color codes generated by our tool can be freely used in any personal or commercial project, including websites, applications, graphics, and designs.',
    },
    {
      question: 'Does the color picker work on mobile devices?',
      answer: 'Yes, our color picker is fully responsive and works perfectly on all devices including smartphones, tablets, and desktop computers. The interface adapts to your screen size for optimal usability.',
    },
    {
      question: 'How do I copy a color code?',
      answer: 'Simply click the copy button next to any color code format (HEX, RGB, or HSL). The code will be instantly copied to your clipboard, and you can paste it anywhere you need.',
    },
  ]

  const toggleFAQ = (index) => {
    setOpenIndex(openIndex === index ? null : index)
  }

  return (
    <section id="faq" className="faq-section">
      <div className="container">
        <div className="section-header">
          <h2 className="section-title">
            Frequently Asked Questions
          </h2>
          <p className="section-subtitle">
            Everything you need to know about our color picker tool
          </p>
        </div>

        <div className="faq-container">
          {faqs.map((faq, index) => (
            <div
              key={index}
              className={`faq-item ${openIndex === index ? 'active' : ''}`}
            >
              <button
                className="faq-question"
                onClick={() => toggleFAQ(index)}
                aria-expanded={openIndex === index}
              >
                <span>{faq.question}</span>
                <svg
                  className="faq-icon"
                  width="24"
                  height="24"
                  viewBox="0 0 24 24"
                  fill="none"
                  stroke="currentColor"
                  strokeWidth="2"
                >
                  <polyline points="6 9 12 15 18 9" />
                </svg>
              </button>
              <div className="faq-answer">
                <p>{faq.answer}</p>
              </div>
            </div>
          ))}
        </div>
      </div>
    </section>
  )
}

export default FAQ
